### PR TITLE
Pretty-print Markdown Tables

### PR DESCRIPTION
**Pull request by Zenjir0**
This is to make things easier to read. I recommend turning off Word Wrap when viewing it. This does not change anything else other than how the tables are formatted in the actual text file. They render the same way. 

I also added a few more icons in the legend. Not all are implemented but they are there. Feel free to remove any if you wish.

### CODE REVIEW

**Comment by DerekTurtleRoe** [comment]
@Zenjir0 First of all, thanks so much for the contribution!

I do have a few suggestions, mostly minor.

1. Separate the legend into 2 sections, one for source availability and one for platform support
2. I don't think we need the images folder since it isn't being used, correct?
3. Remove the bullseye, trophy, and crown

I would also suggest changing the following:
- Green Book to Green book
- Orange Book to Orange book
- Red Book to Red book
- Open-Source Project to Open-source project
- Partially Open-Source or Disputed to Partially open-source or disputed
- Closed-Source Proprietary to Closed-source/proprietary
- Windows OS Support to Runs on Windows
- Mac OS Support to Runs on macOS
- Linux OS Support to Runs on Linux
- BSD OS Support to Runs on BSD
- DOS OS Support to Runs on DOS
- Web-Based to Runs on the web

**Comment by Zenjir0** [comment]
@DerekTurtleRoe Done. All changes made.

**Comment by DerekTurtleRoe** [comment]
@Zenjir0 Thanks so much! This looks great! 😄

**Comment by DerekTurtleRoe** [comment]
I had to merge manually due to conflicts, but thanks so much for your hard work @Zenjir0 ! 😄

**Pull request closed without merging**
