### PR TITLE
Add emojies for Android and iOS

### PR DESCRIPTION
**Pull request by array-in-a-matrix**

### CODE REVIEW

**Comment by DerekTurtleRoe** [comment]
@array-in-a-matrix The apple emoji is already in use for macOS, so I think that might be confusing if something is available for both. If we can resolve that, I'm fine with merging this.

**Comment by array-in-a-matrix** [comment]
> emoji is already in use for macOS

I'm not sure how I even missed this. It was late at night when I PR'd lol. I think either a phone emoji :iphone: or the other apple emoji :green_apple: work fine. 

> change the wording of iPhoneOS/iPadOS to just iOS

Sure, no problem.

**Comment by array-in-a-matrix** [comment]
What should we do regarding Apple's TVOS?

**Comment by DerekTurtleRoe** [comment]
@array-in-a-matrix I think we should just use "iOS" for all of those since technically they are all iOS under the hood. Apple also internally refers to all of them as "iOS" in internal documents.

Also with how locked down and closed Apple devices are, it'll probably be a very long time, if ever, that emulators are released for things like the Apple Vision Pro, so we can always change our mind later if that somehow changes.

**Comment by array-in-a-matrix** [comment]
The Vision Pro has the [GBA4vOS](http://www.gba4iosapp.com/) emulator which can do GB, GBC, and GBA. AFAIK this emulator supports *all* Apple hardware.
Demo: https://www.threads.net/@rileytestut/post/C2-i4tEOlv8

**Comment by DerekTurtleRoe** [comment]
Thanks for the contribution as always 😄

**Pull request merged**
